### PR TITLE
Added Selection Sort

### PR DESCRIPTION
**Pull request by Aditya-y9**
Please add the Hacktoberfest label.

@SwloBr @Joao-Victor-RVG @ Would Love to contribute to your Repository.
Thanks and Regards
Please notify me of any existing problem in this PR.
I would sort it out.

Please add the Hacktoberfest-accepted label once it gets merged

### CODE REVIEW

**Comment by Aditya-y9** [comment]
Please check this PR as well
@SwloBr @Joao-Victor-RVG

**Comment by SwloBr** [comment]
@Aditya-y9, Read README.md of project

Changes to makes
- add gradle module
- implement SortInterface
- Copy Main

**Comment by Aditya-y9** [comment]
Added new commit @SwloBr @Joao-Victor-RVG 
I have added files and changed files as per README 
Thanks and Regards
Please Add the Hacktoberfest and Hacktoberfest-accepted labels

**Comment by Aditya-y9** [comment]
Please check this PR as well

**Comment by Aditya-y9** [comment]
Please notify me if there is any issue so that I can work on it.
Thanks and Regards,
Aditya-y9

**Pull request closed without merging**
